range:
  x: [-0.2, 0.2]
  y: [-0.5, 0.5]
  z: [1.0, 1.2]
  yaw: [0.0, 0.0]
  pitch: [0.0, 0.0]
  roll: [0.0, 0.0]
sensors:
  rgb:
    type: "sensor.camera.rgb"
    image_size_x: 320
    image_size_y: 224
    fov: 100
  seg:
    type: "sensor.camera.semantic_segmentation"
    image_size_x: 320
    image_size_y: 224
    fov: 100
others:
  maps: ["Town01"]
  carla_root: '$HOME/Carla/CARLA_0_9_13'
  save_path: './data'
  samples_per_step: 1


